version: 2

sources:
  - name: citibike
    database: raw
    schema: citibike
    tables:
      - name: trips

  - name: weather
    database: raw
    schema: weather
    tables:
      - name: weather_data
